#python3 main.py  --model_save_path ./output/unsup-consert-base-07260900 --adv_loss_cof 0 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07261000 --warmup_epoch 1 --high_rank 2  --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07261100 --warmup_epoch 1 --high_rank 16 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07261200 --mask_high --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07261300 --mask_high --warmup_epoch 1 --high_rank 8 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#
#
#python3 main.py  --model_save_path ./output/unsup-consert-base-07220100 --seed 4000 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07220200 --high_rank 14 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07071600 --high_rank 16 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07071700 --high_rank 18 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07091430 --warmup_epoch 0.5 --high_rank 20 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 64 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-06290000 --adv_loss_cof 1.0 --low_rate 0.5 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 64 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-06290100 --adv_loss_cof 2.0 --low_rate 0.5 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 64 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-06290200 --adv_loss_cof 0.05 --low_rate 0.5 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 64 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout

#python3 main.py  --model_save_path ./output/unsup-consert-base-07301800 --device cuda:2 --mask_high --mask_rate 0.1 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07301900 --device cuda:2 --mask_high --mask_rate 0.3 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07302000 --device cuda:2 --mask_high --mask_rate 0.4 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07302100 --device cuda:2 --mask_high --mask_rate 0.5 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07302200 --device cuda:2 --mask_high --mask_rate 0.6 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07302300 --device cuda:2 --mask_high --mask_rate 0.7 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07310000 --device cuda:2 --mask_high --mask_rate 0.8 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07310100 --device cuda:2 --mask_high --mask_rate 0.9 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#python3 main.py  --model_save_path ./output/unsup-consert-base-07310200 --device cuda:2 --mask_high --mask_rate 1.0 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout

python3 main.py  --model_save_path ./output/unsup-consert-base-08061000 --device cuda:2 --mask_high --low_rate 0.1 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061100 --device cuda:2 --mask_high --low_rate 0.2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061200 --device cuda:2 --mask_high --low_rate 0.3 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061300 --device cuda:2 --mask_high --low_rate 0.4 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061400 --device cuda:2 --mask_high --low_rate 0.5 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061500 --device cuda:2 --mask_high --low_rate 0.6 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061600 --device cuda:2 --mask_high --low_rate 0.7 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061700 --device cuda:2 --mask_high --low_rate 0.8 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
python3 main.py  --model_save_path ./output/unsup-consert-base-08061800 --device cuda:2 --mask_high --low_rate 0.9 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout



