# python3 main.py  --model_save_path ./output/unsup-consert-base-07291500 --warmup_epoch 0 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07291600 --warmup_epoch 0.5 --high_rank 2  --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07291700 --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07291800 --warmup_epoch 1.5 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07291900 --warmup_epoch 1 --high_rank 4 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07292000 --warmup_epoch 1 --high_rank 6 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07292100 --warmup_epoch 1 --high_rank 8  --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07292200 --warmup_epoch 1 --high_rank 16 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07292300 --mask_loss_cof 0.1 --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07300000 --mask_loss_cof 0.5 --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07300100 --mask_loss_cof 1.5 --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
# python3 main.py  --model_save_path ./output/unsup-consert-base-07300200 --mask_loss_cof 5 --warmup_epoch 1 --high_rank 2 --no_pair --use_apex_amp --apex_amp_opt_level O1 --batch_size 32 --add_cl --cl_loss_only --cl_rate 0.15 --train_data stssick --num_epochs 10 --da_final_1 feature_cutoff --da_final_2 shuffle --cutoff_rate_final_1 0.2 --model_name_or_path bert-base-uncased --force_del --no_dropout
#
#
